server:
  port: 8888

spring:
  application:
    name: Scheduledemo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://xxx.xx.xxx:5306/scheduler_demo_joe?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 222222
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 2
      maxActive: 50
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      logAbandoned: true
      removeAbandoned: true
      removeAbandonedTimeout: 60
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      session-stat-enable : false
      connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    default-property-inclusion: non_null

  http:
    maxTotal: 500
    defaultMaxPerRoute: 200
    connectTimeout: 2000
    connectionRequestTimeout: 500
    maxIdleTime: 100
    socketTimeout: 15000
    https:
      enable: false

org:
  quartz:
    scheduler:
      instanceName: DefaultQuartzScheduler
      instanceId: AUTO

    threadPool:
      threadCount: 5
      threadPriority: 5

    jobStore:
      className: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      useProperties: true
      misfireThreshold: 60000
      tablePrefix: qrtz_
      isClustered: true

    plugin:
      shutdownHook:
        className: org.quartz.plugins.management.ShutdownHookPlugin
        cleanShutdown: TRUE



